// Package genevents provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package genevents

import (
	"time"

	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for EventType.
const (
	IoPlatformOrchestratorDeploymentCreated            EventType = "io.platform-orchestrator.deployment.created"
	IoPlatformOrchestratorDeploymentUpdated            EventType = "io.platform-orchestrator.deployment.updated"
	IoPlatformOrchestratorModuleVersionAdoptionChanged EventType = "io.platform-orchestrator.module.version.adoption-changed"
	IoPlatformOrchestratorRunnerCheckStatus            EventType = "io.platform-orchestrator.runner.check_status"
)

// Valid indicates whether the value is a known member of the EventType enum.
func (e EventType) Valid() bool {
	switch e {
	case IoPlatformOrchestratorDeploymentCreated:
		return true
	case IoPlatformOrchestratorDeploymentUpdated:
		return true
	case IoPlatformOrchestratorModuleVersionAdoptionChanged:
		return true
	case IoPlatformOrchestratorRunnerCheckStatus:
		return true
	default:
		return false
	}
}

// DeploymentChangedData defines model for DeploymentChangedData.
type DeploymentChangedData struct {
	DeploymentId DeploymentId `json:"deployment_id"`
	EnvId        EnvId        `json:"env_id"`
	EnvUuid      EnvUuid      `json:"env_uuid"`
	OrgId        OrgId        `json:"org_id"`
	ProjectId    ProjectId    `json:"project_id"`
	Revision     Revision     `json:"revision"`
	Status       *string      `json:"status,omitempty"`
}

// DeploymentId defines model for DeploymentId.
type DeploymentId = openapi_types.UUID

// EnvId defines model for EnvId.
type EnvId = string

// EnvUuid defines model for EnvUuid.
type EnvUuid = openapi_types.UUID

// EventType defines model for EventType.
type EventType string

// ModuleVersionAdoptionChangedData defines model for ModuleVersionAdoptionChangedData.
type ModuleVersionAdoptionChangedData struct {
	DeploymentId DeploymentId `json:"deployment_id"`
	EnvId        EnvId        `json:"env_id"`
	EnvUuid      EnvUuid      `json:"env_uuid"`
	ObservedAt   time.Time    `json:"observed_at"`
	OrgId        OrgId        `json:"org_id"`
	ProjectId    ProjectId    `json:"project_id"`
}

// OrgId defines model for OrgId.
type OrgId = string

// ProjectId defines model for ProjectId.
type ProjectId = string

// Revision defines model for Revision.
type Revision = int

// RunnerId defines model for RunnerId.
type RunnerId = string

// RunnerStatusCheckData defines model for RunnerStatusCheckData.
type RunnerStatusCheckData struct {
	DeploymentId DeploymentId `json:"deployment_id"`
	OrgId        OrgId        `json:"org_id"`
	RunnerId     RunnerId     `json:"runner_id"`
}
